mqtt_bridge:
  ros__parameters:
    mqtt_address: "172.16.115.101" # "localhost"
    mqtt_port: 1883
    mqtt_username: ""
    mqtt_password: ""
    vda5050_protocol_version: "2.0.0"
    manufacturer_name: "Navitec"
    serial_number: "machine002"

controller:
  ros__parameters:
    robot_name: "machine002Name"
    manufacturer_name: "Navitec"
    serial_number: "machine002"

adapter:
  ros__parameters:
    robot_name: "machine002Name"
    manufacturer_name: "Navitec"
    serial_number: "machine002"
