mqtt_bridge:
  ros__parameters:
    mqtt_address: "localhost"
    mqtt_port: 1883
    mqtt_username: ""
    mqtt_password: ""
    manufacturer_name: "robots"
    serial_number: "robot_1"

controller:
  ros__parameters:
    robot_name: "robot_1"
    manufacturer_name: "robots"
    serial_number: "robot_1"

adapter:
  ros__parameters:
    robot_name: "robot_1"
    manufacturer_name: "robots"
    serial_number: "robot_1"
